<a href="https://colab.research.google.com/github/FranGarcia9/Dato/blob/main/FDGH_Challenge__Linear_Algebra_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CHALLENGE :** LINEAR ALGEBRA EXERCISES.

Una vez visto el ***Hands - On: Linear Algebra***, se presentan la siguientes actividades para que el alumnado pueda repasar y reforzar lo aprendido dentro de la clase de ***Introducción al Álgebra Lineal***. 

# ACTIVIDAD 1. DEFINICIÓN DE MATRICES

In [1]:
import numpy as np

Define un escalar utilizando Numpy

In [26]:
escalar = np.ScalarType 
escalar

10

Define un vector de 5 elementos utilizando Numpy

In [3]:
vect = np.array([2,5,7,4,6])
vect

array([2, 5, 7, 4, 6])

Define una matriz de 2x2 utilizando Numpy

In [5]:
t = np.matrix([
    [1,1,],
    [2,2]
])

t

matrix([[1, 1],
        [2, 2]])

Define una matriz de 5x4 utilizando Numpy

In [11]:
r = np.ones([5,4])
r

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# ACTIVIDAD 2. SUMA Y RESTA DE MATRICES

Realiza la operación de suma de 2 vectores utilizando Numpy

In [12]:
a= np.array([4,8])
b=np.array([2,6])

a+b

array([ 6, 14])

Realiza la operación de suma de 2 matrices utilizando Numpy

In [13]:
t = np.matrix([
    [1,1,],
    [2,2]
])

q = np.matrix([
    [2,4,],
    [4,3]
])

t + q

matrix([[3, 5],
        [6, 5]])

Realiza la operación de suma de 2 matrices que falle debido a tamaño inapropiado de las matrices

In [14]:
t = np.matrix([
    [1,1,],
    [2,2],
    [5,6]
])

q = np.matrix([
    [2,4,],
    [4,3]
])

t + q

ValueError: ignored

#ACTIVIDAD 3. MULTIPLICACIÓN DE MATRICES

Realiza el producto punto de 2 vectore de 3 dimensiones

In [15]:
a= np.array([3,2,4])
b = np.array([2,2,7])


a.dot(b)



38

Realiza el producto cruz de 2 vectores de 3 dimensiones

In [16]:
a = np.array([5, 4, 7])
b = np.array([2, 1, 9])

np.cross(a, b)

array([ 29, -31,  -3])

Realiza la multiplicación de 2 matrices de dimensiones compatibles

In [17]:
t = np.matrix([
    [1,1,],
    [2,2]
])

q = np.matrix([
    [2,4,],
    [4,3]
])

t * q

matrix([[ 6,  7],
        [12, 14]])

Coloca un ejemplo de multiplicación de matrices que falle por dimensiones incompatibles

#ACTIVIDAD 4. DETERMINANTE Y MATRIZ INVERSA

Calcula el determinante de una matriz de 3x3

In [33]:
t = np.matrix([
    [4,9,8],
    [8,5,4],
    [4,9,7]
])


np.linalg.det(t)

51.999999999999986

Calcula la matriz inversa de una matriz de 4x4

In [36]:
p = np.matrix([
    [4,9,8,9],
    [8,5,4,1],
    [4,9,7,5],
    [9,1,4,8]
])
np.linalg.inv(p)

matrix([[ 0.52678571,  0.4375    , -0.75      , -0.17857143],
        [ 2.61607143,  1.5625    , -3.25      , -1.10714286],
        [-4.67857143, -2.75      ,  6.        ,  1.85714286],
        [ 1.41964286,  0.6875    , -1.75      , -0.46428571]])

Coloca un ejemplo de una matriz singular y compruebalo usando Numpy

In [43]:
j = np.matrix([
    [1,1,],
    [2,2]])

if (np.linalg.det(j)):
  print("Matriz no singular")
else:
  print("Es matriz singular")



Es matriz singular
